---
# Source: nginx/templates/networkpolicy.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: my-nginx
  namespace: "helm-demo"
  labels:
    app.kubernetes.io/instance: my-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: 1.31.6
    helm.sh/chart: nginx-25.2.1
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: my-nginx
      app.kubernetes.io/name: nginx
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - ports:
        - port: 8080
        - port: 8443
---
# Source: nginx/templates/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: my-nginx
  namespace: "helm-demo"
  labels:
    app.kubernetes.io/instance: my-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: 1.31.6
    helm.sh/chart: nginx-25.2.1
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: my-nginx
      app.kubernetes.io/name: nginx
---
# Source: nginx/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-nginx
  namespace: "helm-demo"
  labels:
    app.kubernetes.io/instance: my-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: 1.31.6
    helm.sh/chart: nginx-25.2.1
automountServiceAccountToken: false
---
# Source: nginx/templates/tls-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-nginx-tls
  namespace: "helm-demo"
  labels:
    app.kubernetes.io/instance: my-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: 1.31.6
    helm.sh/chart: nginx-25.2.1
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlakNDQW1LZ0F3SUJBZ0lSQUluZ0ttaHpZaVdQN1JmcWZ3cjFpMmN3RFFZSktvWklodmNOQVFFTEJRQXcKRXpFUk1BOEdBMVVFQXhNSWJtZHBibmd0WTJFd0hoY05Nall3T1RNd01UWTFOREV3V2hjTk1qY3dPVE13TVRZMQpOREV3V2pBVE1SRXdEd1lEVlFRREV3aHRlUzF1WjJsdWVEQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQCkFEQ0NBUW9DZ2dFQkFLYk1DOGlpRm9FSFpQeDR6aXJ6NDg1R2szYmZvYndERTQ1WlVCTnZnc2pOV0ZkN2VSK1MKTnByclp4LzIvekVRRCtEL2NsTm0xY2tMVjVOWGdlZFp2ZGNYa3k0bldRTnUwdTBCc0NTVjY5WUFCVURSZXpkQwpPbjZCSG9jdFIrL3RYbW5jM0hOY2JsaWFqZ1NMd3VtS1lUZTVnYUE4RlZqOHpKdnpsYVNYZmVMejlGUUNGT2E0CllFWHRIUjc5UmdTOEt5c2VWaTB1MDFSenV4QlBDK0tiVSsxWCttODJGdUtHekI1OHFBdDFzTlZNUS9ueldVR1UKOXNnNFFqRWpsMXIrQnh5VmFKcnI4cEsxUXpTU3JDY1JVVVJIRGpsZXJRVGVvODZidVRtRlJvNVN6QkJCd2Roawo5Tm1POG9UbmF6MWhnRy9sUjdweDJRempLT2N0bmVnVWpiVUNBd0VBQWFPQnlEQ0J4VEFPQmdOVkhROEJBZjhFCkJBTUNCYUF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01Bd0dBMVVkRXdFQi93UUMKTUFBd0h3WURWUjBqQkJnd0ZvQVVjTHpsMkRQdzBhalp4aC85bG1ISzBDaTh1MEV3WlFZRFZSMFJCRjR3WElJSQpiWGt0Ym1kcGJuaUNFbTE1TFc1bmFXNTRMbWhsYkcwdFpHVnRiNElXYlhrdGJtZHBibmd1YUdWc2JTMWtaVzF2CkxuTjJZNElrYlhrdGJtZHBibmd1YUdWc2JTMWtaVzF2TG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQkErYmhDYjlwWXdZZXA3OUZ1UXVxWnBwZ0Evbm55bkxLMGRXRkNEVmlmeGFLagpLOFdpYi9wVHlzZzE3WHVrMHFaOUx1UEZEZ2lFQXlueHVBdXlML0dPcHhIMk1NSllHU1llWDN0NUk2Y08xZVIyCjlRTWxQbkE5T2tBVHB6SExQYis3YTkrZmtDMUV0K2xVWE81amV0VXZ0VUY3WER6cGRxOUlBeTdsdlNuSkJMdGsKZEJpRjF2ejBSNStBclRjVEgxaXRtUnZNb3pMZVpVOHFmbmxpb2J0emVOMVR6UjBlNDVoNXFHVzFCVitSYzkvZApURkN4UnMvMnR1MkJ0ZjkyUC9UUk0wSFpjMFh0eko0YSt0dnRUNGRvVnpBVXZjYnR3Zy9GeHZpV1FDOHRLT2kvCk5mY29tTStIY3N4bTlZL2NNeWpCK09WNUhLSWlFU2ZhUHViWXhlWlIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBcHN3THlLSVdnUWRrL0hqT0t2UGp6a2FUZHQraHZBTVRqbGxRRTIrQ3lNMVlWM3Q1Ckg1STJtdXRuSC9iL01SQVA0UDl5VTJiVnlRdFhrMWVCNTFtOTF4ZVRMaWRaQTI3UzdRR3dKSlhyMWdBRlFORjcKTjBJNmZvRWVoeTFINysxZWFkemNjMXh1V0pxT0JJdkM2WXBoTjdtQm9Ed1ZXUHpNbS9PVnBKZDk0dlAwVkFJVQo1cmhnUmUwZEh2MUdCTHdyS3g1V0xTN1RWSE83RUU4TDRwdFQ3VmY2YnpZVzRvYk1IbnlvQzNXdzFVeEQrZk5aClFaVDJ5RGhDTVNPWFd2NEhISlZvbXV2eWtyVkROSktzSnhGUlJFY09PVjZ0Qk42anpwdTVPWVZHamxMTUVFSEIKMkdUMDJZN3loT2RyUFdHQWIrVkh1bkhaRE9NbzV5MmQ2QlNOdFFJREFRQUJBb0lCQUF4eG1mVEo3WmFLdXE5Vgo3cFpUR1EwV21ZSFEycWJGZy92OEVIYWl2SEJ4VnNTUURhVkdxZW1TT1F0YXlMSEhCUDJWa1MzdnRNWUpvVUJPCktGUXpqeG93N3J0a0ZzYWtIMUJYUStZMjJTQUtEYStjUnBrRXlUVzVqdndwYTFNc1hsTFU0TGdxam9Ed1p1VlMKbC9sY2FEY0VFVXVuQlRZSHNOYk1WcjhFeVB1RUlPQ0pHQVhGb0tkaWhUU1dsQzlvdnNxb09aT2Vvc1Mya0ZmUApoUFNLcXYvZVR4b3RiYzVPYk9DRndoUzNyc1hkMjJ0VWNjbWpEZVlqTHhMM0xObkhrUDkrVGJnZEtDYTFwK1RICnJBZGVUY1JJbUw1WnFFU3JQOGdPRnJ2QmdoazBLMXg5VkU3TjlKV3dIK0h0NFZUSkZNdXMxaEIzN1gycFpLOWcKWkxxQUhJRUNnWUVBMnA1bnBZMk5sMDBWbGVENHJwQ1g0WFZ2TWczbTNsaWNYZ0NmbzVLTmF3bm5qNHN1WkZ2cQpJbFdWNE0reGFjb0pRL1ZYdUdNUFE0OHhrY0h1aHFFYVZlWVlSOEtIVHpFQXRyV3YzUExjNzVuM1E2QitxR0Q3CkU3UWR5S1BYR0F1Y25YKzluMUo0T3hOZ1lveTJwV0VweFVLUUxnYVJ0WXFJMkdQdHU5V3hCM2tDZ1lFQXcxRkEKRWJoZnR3d1ZXY1dJdEhZTU9peEdzTHM2eHZFby9QSVhtTEJxRmRxazVtNm1DQThtM1JUdG40VkJpKy9jekV1TApPK0hVUTBDQ1ZSUHFUbldwVXVCZ3BzSG5Ha2M0eHBkWHhZemlGVzlXS1FtMGRVTzJwbnJOM2pLSThkZDc3ZUplCmlNcGNoc0tuZHN5czNnUGlWcHZDVmF3cGFJb3BDMG55aHEwZUhSMENnWUVBZ3FkT3JEdEgxcGVrQWRuYzVYN1cKdGxDWHJ1TnVDWTROallSejQ2OFBRMXc4L3FXZ2lTd0JacG1kcENpY0QreEYwMDZLS1ZGU2F2N21FZ1ZEeDBQNgoyRUZXVzNTZnB5MVREdDdRaG96Q2k1T0ptZW9PS0JVbG1LWDVjdEt3RnRmQnRzTUVFWGFaRWoxSFNqNXNYYlFPCjRhd2hQTkNDUG12WDB2TU52a2M4c0lrQ2dZRUFpcklGdHcrZ0dGSGlUMjh3RmtYRmhRR3Y2UXZyUHg0OUp2R2EKdy9oeVBMYVlabkdvUVF6UllpamNYR3k2RU83eGNia3JWQWlYUEhKd21vMmIwcjlHeiswNWRQRTRkTGFpb0pNVAo1dHFXS1BaNHpvZHZ0OTJ2dENSOFVBNitwRTJLV1hCb0JPYitNVXZFczEzQVc1K1NlRUgvQyt0SE5FNzN1bVoyCmJDQSt4QmtDZ1lFQXBkV0I2eDdNNWlTa1hFT0xXdkpSaFl3TmVvWFNNT05LNzhFOVJHNHc1QklVWDhpcWRHSFIKdXh2Nk1UaSsxSU4xYURHeWYybktNRVZwb1hXM0tXRkp3Tk90MFpxVnV5cmJZY1I1T3VEVHM3ajZlYlcweUpTQwptVUtLRStXZEJLQnl0dUZMbHE4Smw0YTJ4SmZ2NzhPZ1J4cFFmSWh5K2Z1VGFZWllSZU1zanMwPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFVENDQWZtZ0F3SUJBZ0lRZE1NTGozWUkzVEYxd2g3dnBxak9iREFOQmdrcWhraUc5dzBCQVFzRkFEQVQKTVJFd0R3WURWUVFERXdodVoybHVlQzFqWVRBZUZ3MHlOakE1TXpBeE5qVTBNVEJhRncweU56QTVNekF4TmpVMApNVEJhTUJNeEVUQVBCZ05WQkFNVENHNW5hVzU0TFdOaE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQTIzN1pKaDFRUVJSeHBieU5mV0dkRjk4K1p0aFduclNvb1B4MEozU05PQjNDRXZEQ2FyTXAKSXh6K01iRXVwRGczbS9mYmIyVS9RL0prSGlkODNoOHBkaTRjamZDenYwTnpmSWJUNVFXaW1xdkluUDBSSVdnVQpXdTFqb3dldDNZYzZZWGE1VmpDaTZ1ZDhJYVBiOXREQ2psWTlZYXlaWWR5aEtGb1JEV3VzV04vOFBESzQvcWdECkVZaVFucktmTldnamdSb2tSOHZpd282TDJPSlptNkhTSEU2Ui9HQU94QXhtTzRmU1MweUlsYjJJM2Z4Yi96NFMKS1VGNEdhd2pkMEt2Z1l3STVTWTJMMzhibXR1Nm9tWUxZclNPU0Z4ZTBaTWpkQzFHNExTVldSLzV2WU9OU3FoLwp2UkxoM0F0MXVvYkwvdFVqUC9KMTlRdlpSL0p5akIzVTd3SURBUUFCbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DCkFxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUIKQWY4d0hRWURWUjBPQkJZRUZIQzg1ZGd6OE5HbzJjWWYvWlpoeXRBb3ZMdEJNQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFDemk4aHdOTlRIMGVOcFozRDVLSXhNelNKY3A0R01Tb0lCVTl3emw4R1VzdTlCNmtSM0ZyYUhxWFU3ClRNWTJ6Y1U3aUdXTXZlL0t2MEhKRXJvNmloamtoTGtkMnNvNVlSMHV2bmxLTnVvcSs5bm9ZYWZleUFSamZ1M0oKait5U1JtMms3L1lrMURtQ0F1cGs4alZXVHprQVJTVWhodmovS1NrdDJHWWJxTEJYelFKRFJNQWRqU3lOMGRmTwp2cEwzb2xYcXdOUkQ0ZmZGNkxSWnpVT3k2VHA3Y0xkRDFqR3dlbGtuSUZ2RVJOU01TZS9XMU0xNk5XQVJEeTdYClVKVXJSclNxMGpHS0lvV3QvdW5UYm03MmdSdkJpLzdIMk5ZdWRkMDN5OFM3ejRXTUZWMEZVQmppN2dwMVJlVm8KT2hSeHI4dWhWbmxOaUI1WTVRNjUyQllHckw4UgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
---
# Source: nginx/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  namespace: "helm-demo"
  labels:
    app.kubernetes.io/instance: my-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: 1.31.6
    helm.sh/chart: nginx-25.2.1
  annotations:
spec:
  type: LoadBalancer
  externalTrafficPolicy: "Cluster"
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app.kubernetes.io/instance: my-nginx
    app.kubernetes.io/name: nginx
---
# Source: nginx/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: "helm-demo"
  labels:
    app.kubernetes.io/instance: my-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: 1.31.6
    helm.sh/chart: nginx-25.2.1
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate: {}
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/instance: my-nginx
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: my-nginx
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: nginx
        app.kubernetes.io/version: 1.31.6
        helm.sh/chart: nginx-25.2.1
      annotations:
    spec:
      
      shareProcessNamespace: false
      serviceAccountName: my-nginx
      automountServiceAccountToken: false
      enableServiceLinks: true
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: my-nginx
                    app.kubernetes.io/name: nginx
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      hostNetwork: false
      hostIPC: false
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        supplementalGroups: []
        sysctls: []
      initContainers:
        - name: preserve-logs-symlinks
          image: registry-1.docker.io/bitnami/nginx:latest
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 150m
              ephemeral-storage: 2Gi
              memory: 192Mi
            requests:
              cpu: 100m
              ephemeral-storage: 50Mi
              memory: 128Mi
          env:
            - name: OPENSSL_FIPS
              value: "yes"
          command:
            - /bin/bash
          args:
            - -ec
            - |
              #!/bin/bash
              . /opt/bitnami/scripts/libfs.sh
              # We copy the logs folder because it has symlinks to stdout and stderr
              if ! is_dir_empty /opt/bitnami/nginx/logs; then
                cp -r /opt/bitnami/nginx/logs /emptydir/app-logs-dir
              fi
          volumeMounts:
            - name: empty-dir
              mountPath: /emptydir
      containers:
        - name: nginx
          image: registry-1.docker.io/bitnami/nginx:latest
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: NGINX_HTTP_PORT_NUMBER
              value: "8080"
            - name: OPENSSL_FIPS
              value: "yes"
            - name: NGINX_HTTPS_PORT_NUMBER
              value: "8443"
          envFrom:
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            tcpSocket:
              port: http
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 150m
              ephemeral-storage: 2Gi
              memory: 192Mi
            requests:
              cpu: 100m
              ephemeral-storage: 50Mi
              memory: 128Mi
          volumeMounts:
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
            - name: empty-dir
              mountPath: /opt/bitnami/nginx/conf
              subPath: app-conf-dir
            - name: empty-dir
              mountPath: /opt/bitnami/nginx/logs
              subPath: app-logs-dir
            - name: empty-dir
              mountPath: /opt/bitnami/nginx/tmp
              subPath: app-tmp-dir
            - name: certificate
              mountPath: /certs
      volumes:
        - name: empty-dir
          emptyDir: {}
        - name: certificate
          secret:
            secretName: my-nginx-tls
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key

